{{-- resources/views/admin/pdf/partials/footer.blade.php
     Shared footer for every PDF export.
     Expects: $generatedAt (Carbon), $generatedBy (string) --}}
<div class="footer">NexHRIS &mdash; Generated by {{ $generatedBy }} on {{ $generatedAt->format('F j, Y g:i A') }}</div>